<div id="page-galeria">
    <div class="grid_12" prefix_1>
        <div class="page-galeria-informacion">
            <div class="content">
                <div id="rg-gallery" class="rg-gallery">
                    <div class="rg-thumbs">                         
                        <div class="es-carousel-wrapper">
                            <div class="es-nav">
                                    <span class="es-nav-prev">Previous</span>
                                    <span class="es-nav-next">Next</span>
                            </div>
                            <div class="es-carousel">
                                <ul>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/01_cerca_de_cuchillla_1.jpg" data-large="img/galeria-principal/01_cerca_de_cuchillla_1.jpg" alt="Instalacion de cerca eléctrica de cuchillas" data-description="¡Ladrones No! - Instalacion de cerca eléctrica de cuchillas" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/02_cerca_electrica_3_condominio_brisa.jpg" data-large="img/galeria-principal/02_cerca_electrica_3_condominio_brisa.jpg" alt="Cerca Eléctrica Condominio Brisa La Palmas" data-description="¡Ladrones No! - Cerca Eléctrica Condominio Brisa La Palmas" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/03_cerca_electrica_17.jpg" data-large="img/galeria-principal/03_cerca_electrica_17.jpg" alt="Cerca eléctrica en domicilio particular" data-description="¡Ladrones No! - Instalación de cerca eléctrica en domicilio particular" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/04_cerca_electrica_16.jpg" data-large="img/galeria-principal/04_cerca_electrica_16.jpg" alt="Instalacion de cerca eléctrica en ALEA Importaciones" data-description="¡Ladrones No! - Instalacion de cerca eléctrica en ALEA Importaciones" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/05_cerca_electrica_15.jpg" data-large="img/galeria-principal/05_cerca_electrica_15.jpg" alt="Instalacion de cerca eléctrica en ALEA Importaciones" data-description="¡Ladrones No! - Instalacion de cerca eléctrica en ALEA Importaciones" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/06_cerca_electrica_20.jpg" data-large="img/galeria-principal/06_cerca_electrica_20.jpg" alt="Instalación de cerca eléctrica" data-description="¡Ladrones No! - Instalación de cerca eléctrica" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/07_cerca_electrica_21.jpg" data-large="img/galeria-principal/07_cerca_electrica_21.jpg" alt="Instalación de cerca eléctrica en domicilio particular" data-description="¡Ladrones No! - Instalación de cerca eléctrica en domicilio particular" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/08_cerca_electrica_con_cuchilla_6.jpg" data-large="img/galeria-principal/08_cerca_electrica_con_cuchilla_6.jpg" alt="Instalación de cerca de cuchillas en domicilio particular" data-description="¡Ladrones No! - Instalación de cerca de cuchillas en domicilio particular" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/09_cerca_electrica_con_cuchilla_2.jpg" data-large="img/galeria-principal/09_cerca_electrica_con_cuchilla_2.jpg" alt="Instalación de cerca de cuchillas en domicilio particular" data-description="¡Ladrones No! - Instalación de cerca de cuchillas en domicilio particular" /></a></li>
                                     <li><a href="#"><img src="img/galeria-principal/thumbnails/10_cerca_de_cuchillla_8.jpg" data-large="img/galeria-principal/10_cerca_de_cuchillla_8.jpg" alt="Cerca de Cuchillas" data-description="¡Ladrones No! - Cerca de Cuchillas" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/11_portada.jpg" data-large="img/galeria-principal/11_portada.jpg" alt="Cerca Electrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>                                     
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/12_cerca_electrica_4.jpg" data-large="img/galeria-principal/12_cerca_electrica_4.jpg" alt="Cerca Eléctrica en domicilio particular" data-description="¡Ladrones No! - Cerca Eléctrica en domicilio particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/13_cerca_electrica_5_condominio_don_lucio.jpg" data-large="img/galeria-principal/13_cerca_electrica_5_condominio_don_lucio.jpg" alt="Instalacion Cerca Eléctrica en Condominio Don Lucio" data-description="¡Ladrones No! - Instalacion Cerca Eléctrica en Condominio Don Lucio" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/14_cerca_electrica_6.jpg" data-large="img/galeria-principal/14_cerca_electrica_6.jpg" alt="Cerca Eléctrica en Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica en Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/15_cerca_electrica_7.jpg" data-large="img/galeria-principal/15_cerca_electrica_7.jpg" alt="Cerca Eléctrica Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/16_cerca_electrica_8.jpg" data-large="img/galeria-principal/16_cerca_electrica_8.jpg" alt="Cerca Eléctrica Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/17_cerca_electrica_con_cuchilla_3.jpg" data-large="img/galeria-principal/17_cerca_electrica_con_cuchilla_3.jpg" alt="Cerca Eléctrica de Cuchilla en Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchilla en Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/18_cerca_electrica_9.jpg" data-large="img/galeria-principal/18_cerca_electrica_9.jpg" alt="Cerca Eléctrica en Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica en Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/19_cerca_electrica_10.jpg" data-large="img/galeria-principal/19_cerca_electrica_10.jpg" alt="Cerca Eléctrica en Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica en Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/20_cerca_electrica_con_cuchilla_4.jpg" data-large="img/galeria-principal/20_cerca_electrica_con_cuchilla_4.jpg" alt="Cerca Eléctrica en Domicilio Particular" data-description="¡Ladrones No! - Cerca Eléctrica en Domicilio Particular" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/21_cerca_electrica_11.jpg" data-large="img/galeria-principal/21_cerca_electrica_11.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/22_cerca_electrica_12.jpg" data-large="img/galeria-principal/22_cerca_electrica_12.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/23_cerca_de_cuchillla_4.jpg" data-large="img/galeria-principal/23_cerca_de_cuchillla_4.jpg" alt="Cerca Eléctrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/24_cerca_de_cuchillla_5.jpg" data-large="img/galeria-principal/24_cerca_de_cuchillla_5.jpg" alt="Cerca Eléctrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/25_cerca_de_cuchillla_6.jpg" data-large="img/galeria-principal/25_cerca_de_cuchillla_6.jpg" alt="Cerca Eléctrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/26_central_electronica.jpg" data-large="img/galeria-principal/26_central_electronica.jpg" alt="Central Eléctronica" data-description="¡Ladrones No! - Central Eléctronica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/27_cerca_electrica_22.jpg" data-large="img/galeria-principal/27_cerca_electrica_22.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/28_cerca_electrica_23.jpg" data-large="img/galeria-principal/28_cerca_electrica_23.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/29_cerca_electrica_24.jpg" data-large="img/galeria-principal/29_cerca_electrica_24.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/30_cerca_electrica_25.jpg" data-large="img/galeria-principal/30_cerca_electrica_25.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/31_cerca_electrica_26.jpg" data-large="img/galeria-principal/31_cerca_electrica_26.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/32_cerca_electrica_inztalando_el_perzonal.jpg" data-large="img/galeria-principal/32_cerca_electrica_inztalando_el_perzonal.jpg" alt="Equipo realizando instalacion de Cerca Eléctrica" data-description="¡Ladrones No! - Equipo realizando instalacion de Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/33_cerca_electrica_inztalando_el_perzonal_2.jpg" data-large="img/galeria-principal/33_cerca_electrica_inztalando_el_perzonal_2.jpg" alt="Equipo realizando instalacion de Cerca Eléctrica" data-description="¡Ladrones No! - Equipo realizando instalacion de Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/34_cerca_electrica_27.jpg" data-large="img/galeria-principal/34_cerca_electrica_27.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/35_cerca_electrica_14.jpg" data-large="img/galeria-principal/35_cerca_electrica_14.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/36_cerca_electrica_1.jpg" data-large="img/galeria-principal/36_cerca_electrica_1.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/37_cerca_electrica_18.jpg" data-large="img/galeria-principal/37_cerca_electrica_18.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/38_cerca_electrica_13.jpg" data-large="img/galeria-principal/38_cerca_electrica_13.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/39_cerca_electrica_19.jpg" data-large="img/galeria-principal/39_cerca_electrica_19.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/40_cerca_electrica_2.jpg" data-large="img/galeria-principal/40_cerca_electrica_2.jpg" alt="Cerca Eléctrica" data-description="¡Ladrones No! - Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/41_central_electronica.jpg" data-large="img/galeria-principal/41_central_electronica.jpg" alt="Central Eléctronica de Cerca Eléctrica" data-description="¡Ladrones No! - Central Eléctronica de Cerca Eléctrica" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/42_cerca_electrica_con_cuchilla_1.jpg" data-large="img/galeria-principal/42_cerca_electrica_con_cuchilla_1.jpg" alt="Cerca Eléctrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>                                    
                                    <li><a href="#"><img src="img/galeria-principal/thumbnails/43_cerca_electrica_con_cuchilla_5.jpg" data-large="img/galeria-principal/43_cerca_electrica_con_cuchilla_5.jpg" alt="Cerca Eléctrica de Cuchillas" data-description="¡Ladrones No! - Cerca Eléctrica de Cuchillas" /></a></li>                                                                                                              
                                </ul>
                            </div>
                        </div>
                        
                    </div> 
                </div>
            </div> 
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="js/responsive-galery/jquery.tmpl.min.js"></script>
<script type="text/javascript" src="js/responsive-galery/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/responsive-galery/jquery.elastislide.js"></script>
<script type="text/javascript" src="js/responsive-galery/gallery.js"></script>